In [79]:
from collections import deque

In [80]:
def bfs(graph, start):
    visited = set()
    queue = deque([start])
    visited.add(start)
    while queue:
        vertex = queue.popleft()
        print(vertex, end=' ')
        for neighbor in graph[vertex]:
            if neighbor not in visited:
                queue.append(neighbor)
                visited.add(neighbor)

In [81]:
graph={
    0:[1, 3],1:[0, 2, 3],2:[1, 4, 5],3:[0, 1, 4],4:[2, 3, 5],5:[2, 4]
}

In [82]:
start_vertex = 0
print("BFS traversal starting from vertex", start_vertex)
bfs(graph, start_vertex)

BFS traversal starting from vertex 0
0 1 3 2 4 5 

In [83]:
#definition
def dfs2(graph, start):
    visited = set()
    stack = [start]
    while stack:
        vertex = stack.pop()
        if vertex not in visited:
            print(vertex, end=' ')
            visited.add(vertex)
            stack.extend(neighbor for neighbor in graph[vertex] if neighbor not in visited)

In [84]:
graph={
    'A':['B', 'S'],
    'B':['A'],
    'C':['D', 'E', 'F', 'S'],
    'D':['C'],
    'E':['C', 'H'],
    'F':['C', 'G'],
    'G':['F', 'H', 'S'],
    'H':['E', 'G'],
    'S':['A', 'C', 'G']
}

In [85]:
# Starting vertex and applying DFS with the second implementation
start_vertex='A'
print("DFS traversal starting from vertex", start_vertex, ":")
dfs2(graph, start_vertex)

DFS traversal starting from vertex A :
A S G H E C F D B 

In [86]:
# heuristic function for A* algorithm
def heuristic(state):
    return np.sum(state!=goal_state)

In [87]:
# A* algorithm implementation
def astar(start_state, goal_state, heuristic):
    priority_queue=PriorityQueue()
    priority_queue.put((0, Node(start_state)))
    while not priority_queue.empty():
        _, current_node = priority_queue.get()
        if np.array_equal(current_node.state, goal_state):
            # Goal state reached, reconstruct path
            path = []
            while current_node:
                path.append(current_node.state)
                current_node = current_node.parent
            return path[::-1]
        for successor_state in get_successors(current_node.state):
            new_cost = current_node.g_score + 1
            new_node = Node(successor_state, parent=current_node, g_score=new_cost, h_score=heuristic(successor_state))
            priority_queue.put((new_node.f_score, new_node))
    return None

In [88]:
# Call the A* algorithm with the initial and final states
result_path=astar(initial_state, goal_state, heuristic)

In [89]:
# Printing result
if result_path is not None:
    print("Solution found:")
    for state in result_path:
        print(state)
else:
    print("Goal state is not reachable.")

Solution found:
[[2 8 3]
 [1 6 4]
 [7 0 5]]
[[2 8 3]
 [1 0 4]
 [7 6 5]]
[[2 0 3]
 [1 8 4]
 [7 6 5]]
[[0 2 3]
 [1 8 4]
 [7 6 5]]
[[1 2 3]
 [0 8 4]
 [7 6 5]]
[[1 2 3]
 [8 0 4]
 [7 6 5]]
